PUT http://localhost:8080/events/5
Content-Type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGV4YW1wbGUuY29tIiwiZXhwIjoxNzU5NTcyMDM1LCJ1c2VySWQiOjJ9.mRJdo_uY8iduWpMRkkrm2JjsKQ05DkCSx0VCTH9v9V8

{
    "name": "Updated test event",
    "description": "A test event",
    "location": "Test location (updated!)",
    "dateTime": "2025-09-28T15:28:00.000Z"
}